- name: Bootstrap development environment
  hosts: localhost
  gather_facts: no
  become: yes
  become_user: root

  vars_files:
        - vars.yml
  pre_tasks:
        - name: Include playbook configuration.
          include_vars: "{{ item }}"
          with_fileglob:
                - vars.yml
                - vars/*.yml
          tags: always

  roles:
        - role: node
