---
# tasks file for common
- name: Check if homebrew is installed
  stat:
        path: /usr/local/bin/brew
  register: homebrew_installed

# - name: Install homebrew
#   shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#   when: not homebrew_installed.stat.exists

- name: Install homebrew packages
  homebrew:
        name: "{{ item }}"
        state: present
        update_homebrew: yes
  loop: "{{ homebrew_installed_packages }}"

- name: Install homebrew cask packages
  homebrew_cask:
        name: "{{ item }}"
        state: present
        update_homebrew: yes
  loop: "{{ homebrew_cask_apps }}"

- name: Install homebrew taps
  homebrew_tap:
        name: "{{ item }}"
        state: present
  loop: "{{ homebrew_taps }}"

- name: Upgrade all homebrew packages
  homebrew:
        update_homebrew: yes
        upgrade_all: yes
  when: homebrew_upgrade_all

- name: Upgrade all homebrew cask packages
  homebrew_cask:
        upgrade_all: yes
  when: homebrew_upgrade_all_cask
